spritesheet:
  name: custom
  px_total: 128
  py_total: 128
  px: 16
  py: 16
  nx: 8
  ny: 8
sprites:
  - name: SHIP_0
    x: 0
    y: 0
  - name: SHIP_1
    x: 1
    y: 0
  - name: SHIP_2
    x: 2
    y: 0
  - name: SHIP_EXPLOSION_0
    x: 0
    y: 1
  - name: SHIP_EXPLOSION_1
    x: 1
    y: 1
  - name: SHIP_EXPLOSION_2
    x: 2
    y: 1
  - name: SHIP_EXPLOSION_3
    x: 3
    y: 1
  - name: SHIP_EXPLOSION_4
    x: 4
    y: 1
  - name: SHIP_EXPLOSION_5
    x: 5
    y: 1
  - name: SHIP_EXPLOSION_6
    x: 6
    y: 1
