spritesheet:
  name: custom
  px_total: 128
  py_total: 128
  px: 16
  py: 16
  nx: 8
  ny: 8
sprites:
  - name: EMPTY
    x: 0
    y: 0
  - name: SHIP_1
    x: 1
    y: 0
  - name: SHIP_2
    x: 2
    y: 0
  - name: SHIP_3
    x: 3
    y: 0
  - name: SHIP_4
    x: 4
    y: 0
  - name: SHIP_5
    x: 5
    y: 0
  - name: SHIP_6
    x: 6
    y: 0
  - name: SHIP_7
    x: 7
    y: 0
  - name: DUDE_1
    x: 0
    y: 5
  - name: FLAG_0
    x: 1
    y: 5
  - name: DUDE_2
    x: 2
    y: 5
  - name: PET_0
    x: 0
    y: 7
  - name: PET_1
    x: 1
    y: 7
  - name: PET_2
    x: 2
    y: 7
